version: '3'
services:
  dremio-single:
    container_name: "dremio"
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9047"
    image: dremio/dremio-oss:24.2.5
    volumes:
      - "${MOUNT_PATH}:/opt/dremio/data"
      - "${CACHE_PATH}:/var/lib/dremio"
      - "${CACHE_PATH}:/var/log/dremio"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
