version: '3'
services:
  elasticsearch-single:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9200"
    volumes:
      - "${MOUNT_PATH}:/usr/share/elasticsearch/data"
      - "${BACKUP_PATH}:/usr/share/elasticsearch/backup"
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    image: elasticsearch:8.11.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=${ELASTIC_SECURITY}
      - http.cors.enabled=${ELASTIC_SECURITY}
      - http.cors.allow-origin="*"
      - http.cors.allow-headers="X-Requested-With,Content-Type,Content-Length,Authorization"
      - "ES_JAVA_OPTS=-Xlog:disable -Xlog:gc=debug:stderr"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
